server:
  port: 8080
devtools:
  livereload:
    enabled: true #是否支持livereload
    port: 35729
  restart:
    enabled: true #是否支持热部署

spring:
  datasource:
    druid:
    url: jdbc:mysql://localhost:3310/springbootlearn?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    minIdle: 5
    maxActive: 200
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testOnBorrow: true
    testOnReturn: false
    testOnWhileIdle: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mybatis/*mapper/**/*.xml
  type-aliases-package: com.neb.springboot.model.*
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      db-type: mysql